# numpy library

In [4]:
import numpy as np
import pandas as pd

In [5]:
car = pd.read_csv('quikr_car.csv')
car.head()

name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000   
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000   
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price   
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000   
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000   

   kms_driven fuel_type  
0  45,000 kms    Petrol  
1      40 kms    Diesel  
2  22,000 kms    Petrol  
3  28,000 kms    Petrol  
4  36,000 kms    Diesel

In [10]:
n = [1,2,3]
type(n)
n

[1, 2, 3]

In [7]:
np1=np.array(n)

In [8]:
type(np1)

numpy.ndarray

In [19]:
print(np1)
print(np1.shape)

[1 2 3]
(3,)


# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [26]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("Shape =", str(c.shape))
print("Shape =",str(d.shape))
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

Shape = (2, 3)
Shape = (2, 2, 3)
0
1
2
3


In [27]:
n9=np.array([[1,2,3,4],[5,6,7,8]]) #2 D array
n9

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
print("Dimention =",str(n9.ndim))

Dimention = 2


In [31]:
n9=np.mean([[1,2,3,4],[5,6,7,8]])
n9

4.5

In [32]:
n4=np.zeros((5,5))#5x5 matrix created

In [34]:
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
n5=np.full((2,3),4)
n5

array([[4, 4, 4],
       [4, 4, 4]])

In [39]:
n6=np.ones((2,3))
n6

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
n7=np.eye(4) #square matrix or identity matrix
n7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
n8=np.random.randint(0,100,9)
n8

array([57, 43, 49, 45, 29, 31, 32,  4, 91])

In [70]:
# n8[:,2]=5

In [72]:
n10=np.random.random((5,3))
n10

array([[0.97445315, 0.21129648, 0.91321376],
       [0.74198375, 0.58014594, 0.91851224],
       [0.02483754, 0.21867137, 0.52317527],
       [0.82172151, 0.09666747, 0.9394295 ],
       [0.92152745, 0.28432744, 0.48310038]])

In [82]:
n10[:,1]=4 # "," says that select the 1 row or cloumn # here it select the 1 column of all rows

In [83]:
n10= np.random.random((4,3))

In [84]:
n10

array([[0.01536414, 0.46813258, 0.99106762],
       [0.85653125, 0.9856466 , 0.37679993],
       [0.03280975, 0.97104965, 0.46070379],
       [0.72435476, 0.74655771, 0.31244535]])

In [85]:
n10[2,:]=13 #select the 2nd row and replace 2nd row by 13 # here it select the 2nd row of all column

In [86]:
n10

array([[ 0.01536414,  0.46813258,  0.99106762],
       [ 0.85653125,  0.9856466 ,  0.37679993],
       [13.        , 13.        , 13.        ],
       [ 0.72435476,  0.74655771,  0.31244535]])

In [92]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.add(x,y)

array([5, 7, 9])

In [128]:
a1 = np.array([1,2,3])
b1= np.array([4,5,6])
# np.sum(b1,axis=0)
np.add(a1,b1)

array([5, 7, 9])

In [116]:
a2= np.array([1,2,3,4,5])
mean=np.mean(a2)
mean

3.0

In [135]:
x =np.array([2,2])
y = np.array([5,4])
Std = np.sqrt(np.sum(np.subtract(x,y)**2))
Std


3.605551275463989